[package]
name = "min"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target = { path = "wit/world.wit" }

[package.metadata.component.dependencies]
